version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "kinesis-test"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-l3q8v1qjqtq2"
s3_prefix = "kinesis-test"
region = "eu-west-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
image_repositories = []
